backend:
  name: github
  repo: jasonsutter87/hugo-victor-test
  branch: master # Branch to update (optional; defaults to master)


media_folder: "src/img/gallery"


collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Custom", name: "custom", widget: "string"}
